import bcrypt from "bcryptjs";

const Data = {
	users: [
		{
			name: "Banu Tryon",
			email: "banutryon@gmail.com",
			password: bcrypt.hashSync("12", 8),
			isAdmin: true,
			isSeller: true,
			seller: {
				name: "Sony",
				logo: "/images/sony.png",
				description: "best seller",
				rating: 4.5,
				numReviews: 120,
			},
		},
		{
			name: "Brandon",
			email: "user1@example.com",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: false,
		},
	],
	products: [
		{
			name: "Playstation 5 Console",
			category: "gaming",
			image: "/images/ps5Game8.jpg",
			price: 499,
			countInStock: 0,
			brand: "Sony",
			rating: 2,
			numReviews: 1423,
			description: `Sony's newest console for the next generation of gaming`,
		},
		// {
		// 	name: "FF7 Remake ",
		// 	category: "gaming",
		// 	image: "/images/game12.jpeg",
		// 	price: 59,
		// 	countInStock: 18,
		// 	brand: "Sony",
		// 	rating: 4.0,
		// 	numReviews: 23,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Demon's Souls ",
		// 	category: "gaming",
		// 	image: "/images/game7.jpeg",
		// 	price: 59,
		// 	countInStock: 18,
		// 	brand: "Sony",
		// 	rating: 4.0,
		// 	numReviews: 23,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Assassins Creed Valhalla",
		// 	category: "gaming",
		// 	image: "/images/game1.jpeg",
		// 	price: 59,
		// 	countInStock: 11,
		// 	brand: "Sony",
		// 	rating: 4.5,
		// 	numReviews: 42,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Spider Man Miles Morales",
		// 	category: "gaming",
		// 	image: "/images/game4.jpeg",
		// 	price: 59,
		// 	countInStock: 12,
		// 	brand: "Sony",
		// 	rating: 5,
		// 	numReviews: 325,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Hit Man",
		// 	category: "gaming",
		// 	image: "/images/game2.jpeg",
		// 	price: 49,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 3.5,
		// 	numReviews: 52,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Devil May Cry 5",
		// 	category: "gaming",
		// 	image: "/images/game3.jpeg",
		// 	price: 59,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 5,
		// 	numReviews: 582,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Rainbow six",
		// 	category: "gaming",
		// 	image: "/images/game5.jpeg",
		// 	price: 49,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 3.5,
		// 	numReviews: 452,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Call of Duty",
		// 	category: "gaming",
		// 	image: "/images/game6.jpeg",
		// 	price: 59,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 3.5,
		// 	numReviews: 103,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Village Resident Evil",
		// 	category: "gaming",
		// 	image: "/images/game8.jpeg",
		// 	price: 59,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 4.5,
		// 	numReviews: 52,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Ratchet and Clank",
		// 	category: "gaming",
		// 	image: "/images/game9.jpeg",
		// 	price: 49,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 4,
		// 	numReviews: 108,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "MK 11",
		// 	category: "gaming",
		// 	image: "/images/game10.jpeg",
		// 	price: 49,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 5,
		// 	numReviews: 321,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Returnal",
		// 	category: "gaming",
		// 	image: "/images/game11.jpeg",
		// 	price: 49,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 3,
		// 	numReviews: 36,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "The Show",
		// 	category: "gaming",
		// 	image: "/images/game13.jpeg",
		// 	price: 49,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 4,
		// 	numReviews: 145,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Sack Boy",
		// 	category: "gaming",
		// 	image: "/images/game14.jpeg",
		// 	price: 49,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 4.5,
		// 	numReviews: 52,
		// 	description: `PS5 game`,
		// },
		// {
		// 	name: "Immortals Fenyx Rising",
		// 	category: "gaming",
		// 	image: "/images/game15.jpeg",
		// 	price: 39,
		// 	countInStock: 16,
		// 	brand: "Sony",
		// 	rating: 3,
		// 	numReviews: 12,
		// 	description: `PS5 game`,
		// },
	],
};
export default Data;
